name: Lint

on:
  pull_request: {}

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Enable Corepack and set Yarn version
        run: |
          corepack enable
          corepack prepare yarn@4.7.0 --activate

      - name: Cache Yarn
        uses: actions/cache@v3
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check Lint
        run: yarn web:lint
